[[cmd]]
shell = "hexit erroneous-inputs/invalid-function-name.hexit"
stdout = { empty = true }
stderr = { file = "outputs/invalid-function-name.txt" }
status = 2

[[cmd]]
shell = "hexit erroneous-inputs/invalid-repeat-amount.hexit"
stdout = { empty = true }
stderr = { file = "outputs/invalid-repeat-amount.txt" }
status = 2

[[cmd]]
shell = "hexit erroneous-inputs/invalid-string-escape.hexit"
stdout = { empty = true }
stderr = { file = "outputs/invalid-string-escape.txt" }
status = 2

[[cmd]]
shell = "hexit erroneous-inputs/stray-things.hexit"
stdout = { empty = true }
stderr = { file = "outputs/stray-things.txt" }
status = 2

[[cmd]]
shell = "hexit erroneous-inputs/unclosed-function.hexit"
stdout = { empty = true }
stderr = { file = "outputs/unclosed-function.txt" }
status = 2

[[cmd]]
shell = "hexit erroneous-inputs/unterminated-form.hexit"
stdout = { empty = true }
stderr = { file = "outputs/unterminated-form.txt" }
status = 2

[[cmd]]
shell = "hexit erroneous-inputs/unterminated-string.hexit"
stdout = { empty = true }
stderr = { file = "outputs/unterminated-string.txt" }
status = 2
