[[cmd]]
environment = { "HEXIT_DEBUG" = "1" }
shell = "hexit ../examples/gzip.hexit"
status = 0
stderr = { string = "DEBUG" }

[[cmd]]
environment = { "HEXIT_DEBUG" = "trace" }
shell = "hexit ../examples/gzip.hexit"
status = 0
stderr = { string = "TRACE" }

# these tests will fail if the gzip example stops being valid
